/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/riscv_top.v:1.1-196.10" *)
module riscv_top(clk, rst_n);
  (* src = "rtl/riscv_top.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "rtl/riscv_top.v:32.17-32.34" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] ex_mem_alu_result;
  (* src = "rtl/riscv_top.v:37.17-37.32" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] ex_mem_mem_size;
  (* src = "rtl/riscv_top.v:36.17-36.30" *)
  (* unused_bits = "0" *)
  wire ex_mem_mem_we;
  (* src = "rtl/riscv_top.v:31.17-31.26" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] ex_mem_pc;
  (* src = "rtl/riscv_top.v:34.17-34.26" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] ex_mem_rd;
  (* src = "rtl/riscv_top.v:33.17-33.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] ex_mem_rd2;
  (* src = "rtl/riscv_top.v:59.24-59.29" *)
  (* unused_bits = "0" *)
  wire flush;
  (* src = "rtl/riscv_top.v:58.17-58.22" *)
  (* unused_bits = "0 1" *)
  wire [1:0] fwd_a;
  (* src = "rtl/riscv_top.v:58.24-58.29" *)
  (* unused_bits = "0 1" *)
  wire [1:0] fwd_b;
  (* src = "rtl/riscv_top.v:17.17-17.29" *)
  wire [3:0] id_ex_alu_op;
  (* src = "rtl/riscv_top.v:18.17-18.30" *)
  wire id_ex_alu_src;
  (* src = "rtl/riscv_top.v:25.17-25.29" *)
  wire id_ex_branch;
  (* src = "rtl/riscv_top.v:15.39-15.48" *)
  wire [31:0] id_ex_imm;
  (* src = "rtl/riscv_top.v:26.17-26.27" *)
  wire id_ex_jump;
  (* src = "rtl/riscv_top.v:21.17-21.29" *)
  wire id_ex_mem_re;
  (* src = "rtl/riscv_top.v:20.17-20.31" *)
  wire [2:0] id_ex_mem_size;
  (* src = "rtl/riscv_top.v:23.17-23.33" *)
  wire id_ex_mem_to_reg;
  (* src = "rtl/riscv_top.v:19.17-19.29" *)
  wire id_ex_mem_we;
  (* src = "rtl/riscv_top.v:14.17-14.25" *)
  wire [31:0] id_ex_pc;
  (* src = "rtl/riscv_top.v:16.39-16.47" *)
  wire [4:0] id_ex_rd;
  (* src = "rtl/riscv_top.v:15.17-15.26" *)
  wire [31:0] id_ex_rd1;
  (* src = "rtl/riscv_top.v:15.28-15.37" *)
  wire [31:0] id_ex_rd2;
  (* src = "rtl/riscv_top.v:22.17-22.29" *)
  wire id_ex_reg_we;
  (* src = "rtl/riscv_top.v:24.17-24.33" *)
  wire [1:0] id_ex_result_sel;
  (* src = "rtl/riscv_top.v:16.17-16.26" *)
  wire [4:0] id_ex_rs1;
  (* src = "rtl/riscv_top.v:16.28-16.37" *)
  wire [4:0] id_ex_rs2;
  (* src = "rtl/riscv_top.v:10.17-10.28" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] if_id_instr;
  (* src = "rtl/riscv_top.v:30.17-30.23" *)
  (* unused_bits = "0" *)
  wire pc_sel;
  (* src = "rtl/riscv_top.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* hdlname = "u_ex clk" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:2.24-2.27" *)
  (* unused_bits = "0" *)
  wire \u_ex.clk ;
  (* hdlname = "u_ex ex_mem_alu_result" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:23.24-23.41" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_ex.ex_mem_alu_result ;
  (* hdlname = "u_ex ex_mem_alu_result_reg" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:28.24-28.45" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_ex.ex_mem_alu_result_reg ;
  (* hdlname = "u_ex ex_mem_mem_size" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:33.24-33.39" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] \u_ex.ex_mem_mem_size ;
  (* hdlname = "u_ex ex_mem_mem_we" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:32.24-32.37" *)
  (* unused_bits = "0" *)
  wire \u_ex.ex_mem_mem_we ;
  (* hdlname = "u_ex ex_mem_pc" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:27.24-27.33" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_ex.ex_mem_pc ;
  (* hdlname = "u_ex ex_mem_rd" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:30.24-30.33" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] \u_ex.ex_mem_rd ;
  (* hdlname = "u_ex ex_mem_rd2" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:29.24-29.34" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_ex.ex_mem_rd2 ;
  (* hdlname = "u_ex fwd_a" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:21.24-21.29" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \u_ex.fwd_a ;
  (* hdlname = "u_ex fwd_b" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:22.24-22.29" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \u_ex.fwd_b ;
  (* hdlname = "u_ex id_ex_alu_op" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:11.24-11.36" *)
  wire [3:0] \u_ex.id_ex_alu_op ;
  (* hdlname = "u_ex id_ex_alu_src" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:12.24-12.37" *)
  wire \u_ex.id_ex_alu_src ;
  (* hdlname = "u_ex id_ex_branch" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:19.24-19.36" *)
  wire \u_ex.id_ex_branch ;
  (* hdlname = "u_ex id_ex_imm" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:7.24-7.33" *)
  wire [31:0] \u_ex.id_ex_imm ;
  (* hdlname = "u_ex id_ex_jump" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:20.24-20.34" *)
  wire \u_ex.id_ex_jump ;
  (* hdlname = "u_ex id_ex_mem_re" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:15.24-15.36" *)
  wire \u_ex.id_ex_mem_re ;
  (* hdlname = "u_ex id_ex_mem_size" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:14.24-14.38" *)
  wire [2:0] \u_ex.id_ex_mem_size ;
  (* hdlname = "u_ex id_ex_mem_to_reg" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:17.24-17.40" *)
  wire \u_ex.id_ex_mem_to_reg ;
  (* hdlname = "u_ex id_ex_mem_we" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:13.24-13.36" *)
  wire \u_ex.id_ex_mem_we ;
  (* hdlname = "u_ex id_ex_pc" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:4.24-4.32" *)
  wire [31:0] \u_ex.id_ex_pc ;
  (* hdlname = "u_ex id_ex_rd" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:10.24-10.32" *)
  wire [4:0] \u_ex.id_ex_rd ;
  (* hdlname = "u_ex id_ex_rd1" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:5.24-5.33" *)
  wire [31:0] \u_ex.id_ex_rd1 ;
  (* hdlname = "u_ex id_ex_rd2" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:6.24-6.33" *)
  wire [31:0] \u_ex.id_ex_rd2 ;
  (* hdlname = "u_ex id_ex_reg_we" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:16.24-16.36" *)
  wire \u_ex.id_ex_reg_we ;
  (* hdlname = "u_ex id_ex_result_sel" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:18.24-18.40" *)
  wire [1:0] \u_ex.id_ex_result_sel ;
  (* hdlname = "u_ex id_ex_rs1" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:8.24-8.33" *)
  wire [4:0] \u_ex.id_ex_rs1 ;
  (* hdlname = "u_ex id_ex_rs2" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:9.24-9.33" *)
  wire [4:0] \u_ex.id_ex_rs2 ;
  (* hdlname = "u_ex pc_sel" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:26.24-26.30" *)
  (* unused_bits = "0" *)
  wire \u_ex.pc_sel ;
  (* hdlname = "u_ex rst_n" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/ex_stage.v:3.24-3.29" *)
  (* unused_bits = "0" *)
  wire \u_ex.rst_n ;
  (* hdlname = "u_ex u_alu alu_op" *)
  (* src = "rtl/riscv_top.v:117.14-154.6|rtl/alu.v:4.24-4.30|rtl/ex_stage.v:57.9-57.98" *)
  wire [3:0] \u_ex.u_alu.alu_op ;
  (* hdlname = "u_haz ex_mem_rd" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:5.24-5.33" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] \u_haz.ex_mem_rd ;
  (* hdlname = "u_haz flush" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:20.24-20.29" *)
  (* unused_bits = "0" *)
  wire \u_haz.flush ;
  (* hdlname = "u_haz fwd_a" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:16.24-16.29" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \u_haz.fwd_a ;
  (* hdlname = "u_haz fwd_b" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:17.24-17.29" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \u_haz.fwd_b ;
  (* hdlname = "u_haz id_ex_mem_re" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:13.24-13.36" *)
  wire \u_haz.id_ex_mem_re ;
  (* hdlname = "u_haz id_ex_rd" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:9.24-9.32" *)
  wire [4:0] \u_haz.id_ex_rd ;
  (* hdlname = "u_haz id_ex_rs1" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:3.24-3.33" *)
  wire [4:0] \u_haz.id_ex_rs1 ;
  (* hdlname = "u_haz id_ex_rs2" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:4.24-4.33" *)
  wire [4:0] \u_haz.id_ex_rs2 ;
  (* hdlname = "u_haz pc_sel" *)
  (* src = "rtl/riscv_top.v:178.17-194.6|rtl/hazard_unit.v:14.24-14.30" *)
  (* unused_bits = "0" *)
  wire \u_haz.pc_sel ;
  (* hdlname = "u_id clk" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:2.24-2.27" *)
  (* unused_bits = "0" *)
  wire \u_id.clk ;
  (* hdlname = "u_id flush" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:5.24-5.29" *)
  (* unused_bits = "0" *)
  wire \u_id.flush ;
  (* hdlname = "u_id id_ex_alu_op" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:23.24-23.36" *)
  wire [3:0] \u_id.id_ex_alu_op ;
  (* hdlname = "u_id id_ex_alu_src" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:24.24-24.37" *)
  wire \u_id.id_ex_alu_src ;
  (* hdlname = "u_id id_ex_branch" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:31.24-31.36" *)
  wire \u_id.id_ex_branch ;
  (* hdlname = "u_id id_ex_imm" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:19.24-19.33" *)
  wire [31:0] \u_id.id_ex_imm ;
  (* hdlname = "u_id id_ex_jump" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:32.24-32.34" *)
  wire \u_id.id_ex_jump ;
  (* hdlname = "u_id id_ex_mem_re" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:27.24-27.36" *)
  wire \u_id.id_ex_mem_re ;
  (* hdlname = "u_id id_ex_mem_size" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:26.24-26.38" *)
  wire [2:0] \u_id.id_ex_mem_size ;
  (* hdlname = "u_id id_ex_mem_to_reg" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:29.24-29.40" *)
  wire \u_id.id_ex_mem_to_reg ;
  (* hdlname = "u_id id_ex_mem_we" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:25.24-25.36" *)
  wire \u_id.id_ex_mem_we ;
  (* hdlname = "u_id id_ex_pc" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:16.24-16.32" *)
  wire [31:0] \u_id.id_ex_pc ;
  (* hdlname = "u_id id_ex_rd" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:22.24-22.32" *)
  wire [4:0] \u_id.id_ex_rd ;
  (* hdlname = "u_id id_ex_rd1" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:17.24-17.33" *)
  wire [31:0] \u_id.id_ex_rd1 ;
  (* hdlname = "u_id id_ex_rd2" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:18.24-18.33" *)
  wire [31:0] \u_id.id_ex_rd2 ;
  (* hdlname = "u_id id_ex_reg_we" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:28.24-28.36" *)
  wire \u_id.id_ex_reg_we ;
  (* hdlname = "u_id id_ex_result_sel" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:30.24-30.40" *)
  wire [1:0] \u_id.id_ex_result_sel ;
  (* hdlname = "u_id id_ex_rs1" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:20.24-20.33" *)
  wire [4:0] \u_id.id_ex_rs1 ;
  (* hdlname = "u_id id_ex_rs2" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:21.24-21.33" *)
  wire [4:0] \u_id.id_ex_rs2 ;
  (* hdlname = "u_id if_id_instr" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:6.24-6.35" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_id.if_id_instr ;
  (* hdlname = "u_id imm_b" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:46.17-46.22" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_id.imm_b ;
  (* hdlname = "u_id imm_j" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:48.17-48.22" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_id.imm_j ;
  (* hdlname = "u_id imm_s" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:45.17-45.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_id.imm_s ;
  (* hdlname = "u_id imm_u" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:47.17-47.22" *)
  (* unused_bits = "12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_id.imm_u ;
  (* hdlname = "u_id opcode" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:36.16-36.22" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] \u_id.opcode ;
  (* hdlname = "u_id rd_addr" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:39.16-39.23" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] \u_id.rd_addr ;
  (* hdlname = "u_id rst_n" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/id_stage.v:3.24-3.29" *)
  (* unused_bits = "0" *)
  wire \u_id.rst_n ;
  (* hdlname = "u_id u_regfile clk" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/regfile.v:2.24-2.27|rtl/id_stage.v:197.13-206.6" *)
  (* unused_bits = "0" *)
  wire \u_id.u_regfile.clk ;
  (* hdlname = "u_id u_regfile i" *)
  (* src = "rtl/riscv_top.v:86.14-115.6|rtl/regfile.v:13.13-13.14|rtl/id_stage.v:197.13-206.6" *)
  wire [31:0] \u_id.u_regfile.i ;
  (* hdlname = "u_if clk" *)
  (* src = "rtl/riscv_top.v:73.14-84.6|rtl/if_stage.v:2.24-2.27" *)
  (* unused_bits = "0" *)
  wire \u_if.clk ;
  (* hdlname = "u_if flush" *)
  (* src = "rtl/riscv_top.v:73.14-84.6|rtl/if_stage.v:5.24-5.29" *)
  (* unused_bits = "0" *)
  wire \u_if.flush ;
  (* hdlname = "u_if if_id_instr" *)
  (* src = "rtl/riscv_top.v:73.14-84.6|rtl/if_stage.v:11.24-11.35" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_if.if_id_instr ;
  (* hdlname = "u_if pc_sel" *)
  (* src = "rtl/riscv_top.v:73.14-84.6|rtl/if_stage.v:7.24-7.30" *)
  (* unused_bits = "0" *)
  wire \u_if.pc_sel ;
  (* hdlname = "u_if rst_n" *)
  (* src = "rtl/riscv_top.v:73.14-84.6|rtl/if_stage.v:3.24-3.29" *)
  (* unused_bits = "0" *)
  wire \u_if.rst_n ;
  (* hdlname = "u_mem addr" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:34.17-34.21" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mem.addr ;
  (* hdlname = "u_mem clk" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:2.24-2.27" *)
  (* unused_bits = "0" *)
  wire \u_mem.clk ;
  (* hdlname = "u_mem ex_mem_alu_result" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:6.24-6.41" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_mem.ex_mem_alu_result ;
  (* hdlname = "u_mem ex_mem_mem_size" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:10.24-10.39" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] \u_mem.ex_mem_mem_size ;
  (* hdlname = "u_mem ex_mem_mem_we" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:9.24-9.37" *)
  (* unused_bits = "0" *)
  wire \u_mem.ex_mem_mem_we ;
  (* hdlname = "u_mem ex_mem_pc" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:5.24-5.33" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_mem.ex_mem_pc ;
  (* hdlname = "u_mem ex_mem_rd" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:8.24-8.33" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] \u_mem.ex_mem_rd ;
  (* hdlname = "u_mem ex_mem_rd2" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:7.24-7.34" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_mem.ex_mem_rd2 ;
  (* hdlname = "u_mem j" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:28.13-28.14" *)
  wire [31:0] \u_mem.j ;
  (* hdlname = "u_mem rst_n" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:3.24-3.29" *)
  (* unused_bits = "0" *)
  wire \u_mem.rst_n ;
  (* hdlname = "u_mem wdata" *)
  (* src = "rtl/riscv_top.v:156.15-176.6|rtl/mem_stage.v:35.17-35.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \u_mem.wdata ;
  assign ex_mem_alu_result = \u_ex.ex_mem_alu_result ;
  assign ex_mem_mem_size = \u_ex.ex_mem_mem_size ;
  assign ex_mem_mem_we = \u_ex.ex_mem_mem_we ;
  assign ex_mem_pc = \u_ex.ex_mem_pc ;
  assign ex_mem_rd = \u_ex.ex_mem_rd ;
  assign ex_mem_rd2 = \u_ex.ex_mem_rd2 ;
  assign flush = \u_ex.pc_sel ;
  assign fwd_a = \u_ex.fwd_a ;
  assign fwd_b = \u_ex.fwd_b ;
  assign id_ex_alu_op = 4'h0;
  assign id_ex_alu_src = 1'h0;
  assign id_ex_branch = 1'h0;
  assign id_ex_imm = 32'd0;
  assign id_ex_jump = 1'h0;
  assign id_ex_mem_re = 1'h0;
  assign id_ex_mem_size = 3'h0;
  assign id_ex_mem_to_reg = 1'h0;
  assign id_ex_mem_we = 1'h0;
  assign id_ex_pc = 32'd0;
  assign id_ex_rd = 5'h00;
  assign id_ex_rd1 = 32'd0;
  assign id_ex_rd2 = 32'd0;
  assign id_ex_reg_we = 1'h0;
  assign id_ex_result_sel = 2'h0;
  assign id_ex_rs1 = 5'h00;
  assign id_ex_rs2 = 5'h00;
  assign if_id_instr[11:0] = \u_id.if_id_instr [11:0];
  assign pc_sel = \u_ex.pc_sel ;
  assign \u_ex.clk  = clk;
  assign \u_ex.ex_mem_alu_result_reg  = \u_ex.ex_mem_alu_result ;
  assign \u_ex.id_ex_alu_op  = 4'h0;
  assign \u_ex.id_ex_alu_src  = 1'h0;
  assign \u_ex.id_ex_branch  = 1'h0;
  assign \u_ex.id_ex_imm  = 32'd0;
  assign \u_ex.id_ex_jump  = 1'h0;
  assign \u_ex.id_ex_mem_re  = 1'h0;
  assign \u_ex.id_ex_mem_size  = 3'h0;
  assign \u_ex.id_ex_mem_to_reg  = 1'h0;
  assign \u_ex.id_ex_mem_we  = 1'h0;
  assign \u_ex.id_ex_pc  = 32'd0;
  assign \u_ex.id_ex_rd  = 5'h00;
  assign \u_ex.id_ex_rd1  = 32'd0;
  assign \u_ex.id_ex_rd2  = 32'd0;
  assign \u_ex.id_ex_reg_we  = 1'h0;
  assign \u_ex.id_ex_result_sel  = 2'h0;
  assign \u_ex.id_ex_rs1  = 5'h00;
  assign \u_ex.id_ex_rs2  = 5'h00;
  assign \u_ex.rst_n  = rst_n;
  assign \u_ex.u_alu.alu_op  = 4'h0;
  assign \u_haz.ex_mem_rd  = \u_ex.ex_mem_rd ;
  assign \u_haz.flush  = \u_ex.pc_sel ;
  assign \u_haz.fwd_a  = \u_ex.fwd_a ;
  assign \u_haz.fwd_b  = \u_ex.fwd_b ;
  assign \u_haz.id_ex_mem_re  = 1'h0;
  assign \u_haz.id_ex_rd  = 5'h00;
  assign \u_haz.id_ex_rs1  = 5'h00;
  assign \u_haz.id_ex_rs2  = 5'h00;
  assign \u_haz.pc_sel  = \u_ex.pc_sel ;
  assign \u_id.clk  = clk;
  assign \u_id.flush  = \u_ex.pc_sel ;
  assign \u_id.id_ex_alu_op  = 4'h0;
  assign \u_id.id_ex_alu_src  = 1'h0;
  assign \u_id.id_ex_branch  = 1'h0;
  assign \u_id.id_ex_imm  = 32'd0;
  assign \u_id.id_ex_jump  = 1'h0;
  assign \u_id.id_ex_mem_re  = 1'h0;
  assign \u_id.id_ex_mem_size  = 3'h0;
  assign \u_id.id_ex_mem_to_reg  = 1'h0;
  assign \u_id.id_ex_mem_we  = 1'h0;
  assign \u_id.id_ex_pc  = 32'd0;
  assign \u_id.id_ex_rd  = 5'h00;
  assign \u_id.id_ex_rd1  = 32'd0;
  assign \u_id.id_ex_rd2  = 32'd0;
  assign \u_id.id_ex_reg_we  = 1'h0;
  assign \u_id.id_ex_result_sel  = 2'h0;
  assign \u_id.id_ex_rs1  = 5'h00;
  assign \u_id.id_ex_rs2  = 5'h00;
  assign { \u_id.imm_b [11], \u_id.imm_b [4:0] } = { \u_id.if_id_instr [7], \u_id.if_id_instr [11:8], 1'h0 };
  assign \u_id.imm_j [0] = 1'h0;
  assign \u_id.imm_s [4:0] = \u_id.if_id_instr [11:7];
  assign \u_id.imm_u [11:0] = 12'h000;
  assign \u_id.opcode  = \u_id.if_id_instr [6:0];
  assign \u_id.rd_addr  = \u_id.if_id_instr [11:7];
  assign \u_id.rst_n  = rst_n;
  assign \u_id.u_regfile.clk  = clk;
  assign \u_id.u_regfile.i  = 32'd32;
  assign \u_if.clk  = clk;
  assign \u_if.flush  = \u_ex.pc_sel ;
  assign \u_if.if_id_instr [11:0] = \u_id.if_id_instr [11:0];
  assign \u_if.pc_sel  = \u_ex.pc_sel ;
  assign \u_if.rst_n  = rst_n;
  assign \u_mem.addr  = \u_ex.ex_mem_alu_result [9:2];
  assign \u_mem.clk  = clk;
  assign \u_mem.ex_mem_alu_result  = \u_ex.ex_mem_alu_result ;
  assign \u_mem.ex_mem_mem_size  = \u_ex.ex_mem_mem_size ;
  assign \u_mem.ex_mem_mem_we  = \u_ex.ex_mem_mem_we ;
  assign \u_mem.ex_mem_pc  = \u_ex.ex_mem_pc ;
  assign \u_mem.ex_mem_rd  = \u_ex.ex_mem_rd ;
  assign \u_mem.ex_mem_rd2  = \u_ex.ex_mem_rd2 ;
  assign \u_mem.j  = 32'd256;
  assign \u_mem.rst_n  = rst_n;
  assign \u_mem.wdata  = \u_ex.ex_mem_rd2 ;
endmodule
